# Generated by Django 4.2.6 on 2023-11-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sticker', models.CharField(max_length=255)),
                ('building', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=255)),
                ('block', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('comment_1', models.CharField(max_length=255)),
                ('wtf', models.CharField(max_length=255)),
                ('netmask', models.CharField(max_length=255)),
                ('comment_2', models.CharField(max_length=255)),
                ('sn', models.CharField(max_length=255)),
                ('mac', models.CharField(max_length=255)),
                ('comment_3', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
            ],
        ),
    ]
