# Generated by Django 4.2.6 on 2023-11-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_comment_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='sticker',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наклейка'),
        ),
    ]
