# Generated by Django 4.2.6 on 2023-11-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_device_sticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='sticker',
            field=models.PositiveSmallIntegerField(blank=True, null=True, unique=True, verbose_name='Наклейка'),
        ),
    ]
