# Generated by Django 4.2.6 on 2023-11-11 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_location_alter_device_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Локация', 'verbose_name_plural': 'Локации'},
        ),
        migrations.RemoveField(
            model_name='device',
            name='comment_1',
        ),
        migrations.RemoveField(
            model_name='device',
            name='comment_2',
        ),
        migrations.RemoveField(
            model_name='device',
            name='comment_3',
        ),
        migrations.AddField(
            model_name='location',
            name='block',
            field=models.CharField(max_length=255, null=True, verbose_name='Район'),
        ),
        migrations.AddField(
            model_name='location',
            name='building',
            field=models.CharField(max_length=255, null=True, verbose_name='Дом'),
        ),
        migrations.AddField(
            model_name='location',
            name='street',
            field=models.CharField(max_length=255, null=True, verbose_name='Улица / Проезд'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.device', verbose_name='Оборудование'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=1000, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='device',
            name='state',
            field=models.CharField(blank=True, choices=[('И', 'Используется'), ('У', 'Установлен'), ('Д', 'Демонтирован'), ('З', 'В запасе'), ('С', 'Вышел из строя')], default=('З', 'В запасе'), max_length=1, null=True, verbose_name='Текущий статус'),
        ),
    ]
