# Generated by Django 4.2.6 on 2023-11-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_location_options_remove_device_comment_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='location',
            field=models.CharField(max_length=255, null=True, verbose_name='Локация'),
        ),
    ]
