# Generated by Django 4.2.6 on 2023-11-11 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_device_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.ForeignKey(max_length=255, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.location', verbose_name='Локация'),
        ),
    ]
