# Generated by Django 4.2.6 on 2023-11-11 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_device_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='block',
        ),
        migrations.RemoveField(
            model_name='device',
            name='building',
        ),
        migrations.RemoveField(
            model_name='device',
            name='street',
        ),
    ]
