version: "3.8"

services:

  db:
    container_name: dev_database
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - dev_db_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

  app:
    container_name: dev_application
    build:
      context: ../devices/
    restart: always
    ports:
      - "8001:8000"
    depends_on:
      - db

  dev:
    container_name: dev_webserver
    image: nginx:1.21.3-alpine
    restart: always
    ports:
      - "81:80"
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
      - dev_static_value:/var/html/static/
      - dev_media_value:/var/html/media/
    depends_on:
      - app

volumes:
  dev_db_data:
    name: dev_devices_db_vol
  dev_static_value:
    name: dev_devices_static_vol
  dev_media_value:
    name: dev_devices_media_vol
