version: "3.8"

services:
  app:
    build:
      context: ../devices/
    volumes:
      - dev_db:/devices/database
    restart: always
    ports:
      - "8000:8000"

volumes:
  dev_db:
    name: dev_db
