version: "3.8"

services:

  db_dev:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - db_data_dev:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

  devices_app_dev:
    build:
      context: ../devices/
    restart: always
    ports:
      - "5000:8000"
    depends_on:
      - db_dev

  nginx_dev:
    image: nginx:1.21.3-alpine
    restart: always
    ports:
      - "81:80"
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
      - static_value_dev:/var/html/static/
      - media_value_dev:/var/html/media/
    depends_on:
      - devices_app_dev


volumes:
  db_data_dev:
  static_value_dev:
  media_value_dev:

# The commented out section below is an example of how to define a PostgreSQL
# database that your application can use. `depends_on` tells Docker Compose to
# start the database before your application. The `db-data` volume persists the
# database data between container restarts. The `db-password` secret is used
# to set the database password. You must create `db/password.txt` and add
# a password of your choosing to it before running `docker compose up`.
#     depends_on:
#       db:
#         condition: service_healthy
#   db:
#     image: postgres
#     restart: always
#     user: postgres
#     secrets:
#       - db-password
#     volumes:
#       - db-data:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_DB=example
#       - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
#     expose:
#       - 5432
#     healthcheck:
#       test: [ "CMD", "pg_isready" ]
#       interval: 10s
#       timeout: 5s
#       retries: 5
# volumes:
#   db-data:
# secrets:
#   db-password:
#     file: db/password.txt

